### ISSUE TITLE
Package `converter` as an imported library.

### ISSUE THREAD

**Issue by AntonDzyk** [MariaMaximova/convert_temp#16]
**Is your feature request related to a problem? Please describe.**
If I import converter in my project. I will have only function with convert variables, but if I need convert string with parameters for converter, I need copy variables and logic in main.py.

**Describe the solution you'd like**
main.py should be contains only import and run converter with args.
Better use __main__.py (instead of ```if __name__ == '__main__'``` in main.py) 

**Describe alternatives you've considered**

**Additional context**
Show main for `pip` or `flake8`
https://github.com/pypa/pip/blob/main/src/pip/__main__.py
https://github.com/PyCQA/flake8/blob/main/src/flake8/__main__.py
https://habr.com/ru/post/456214/

**Comment by MariaMaximova** [comment]
Was resolved in #15
